all:	
	gcc -g -Wall -o prob1 prob1.c -lpthread -lrt
	gcc -g -Wall -o prob2 prob2.c -lpthread -lrt
prob1:	
	gcc -g -Wall -o prob1 prob1.c -lpthread -lrt
prob2:
	gcc -g -Wall -o prob2 prob2.c -lpthread -lrt
update:
	cp ./* /scratch/fall2016/cs444-135/concurrency4
clean:
	rm main


